/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastroclientesnb;

import DAO.ClienteMapDAO;
import DAO.IClienteDAO;
import Domain.Cliente;
import Util.ValidacaoUtil;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Objects;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author games
 */
public class TelaCadastro extends javax.swing.JFrame {
    private DefaultTableModel model = new DefaultTableModel();
    private ValidacaoUtil valid= new ValidacaoUtil();
    private IClienteDAO clienteDAO = new ClienteMapDAO();
    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1Nome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTNSalvar = new javax.swing.JButton();
        jLabel1Nome1 = new javax.swing.JLabel();
        jLabel1Nome2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtEndereco = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtTelefone = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtEmail = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtNome = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtCPF = new javax.swing.JTextPane();
        limpar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        atualizarCadastro = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1Nome.setText("Telefone:");

        jLabel2.setText("CPF:");

        BTNSalvar.setText("Salvar");
        BTNSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSalvarActionPerformed(evt);
            }
        });

        jLabel1Nome1.setText("Nome: ");

        jLabel1Nome2.setText("Email:");

        txtEndereco.setColumns(20);
        txtEndereco.setRows(5);
        jScrollPane5.setViewportView(txtEndereco);

        jLabel3.setText("Endereço:");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tabela);

        jScrollPane9.setViewportView(txtTelefone);

        jScrollPane10.setViewportView(txtEmail);

        jScrollPane12.setViewportView(txtNome);

        jScrollPane13.setViewportView(txtCPF);

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        atualizarCadastro.setText("Atualizar Cadastro");
        atualizarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarCadastroActionPerformed(evt);
            }
        });

        jMenu1.setText("Opções");

        JMenuItemSair.setText("Sair");
        JMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(JMenuItemSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1Nome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTNSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(limpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(atualizarCadastro)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1Nome2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1Nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 43, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1Nome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1Nome2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNSalvar)
                    .addComponent(limpar)
                    .addComponent(excluir)
                    .addComponent(atualizarCadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemSairActionPerformed
                int result = JOptionPane.showConfirmDialog(this, "Deseja saír", "Sair",
                       JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE); 
        if(result == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_JMenuItemSairActionPerformed

    private void BTNSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSalvarActionPerformed
        
        
        String nome = txtNome.getText();
        String cpf = txtCPF.getText();
        String telefone = txtTelefone.getText();
        String email = txtEmail.getText();
        String endereco = txtEndereco.getText();
        String dados = (nome+","+cpf+","+telefone+","+email+","+endereco);
        
        if(!valid.isValidCampo(nome,cpf,telefone,email,endereco)){           
                JOptionPane.showMessageDialog(null,"Campo invalido","Erro",JOptionPane.ERROR_MESSAGE );            
        }
        
        String retorno = clienteDAO.cadastrarCliente(nome,cpf,telefone,email,endereco);
        
        if(retorno == "cadastrado"){
            model.addRow(new Object[]{nome,cpf,telefone,email,endereco});
            JOptionPane.showMessageDialog(null,"Cliente Cadastrado!","Cadastro",JOptionPane.INFORMATION_MESSAGE );
            txtNome.setText("");
            txtCPF.setText("");
            txtTelefone.setText("");
            txtEmail.setText("");
            txtEndereco.setText("");
            
        }else if(retorno == "existente"){
                JOptionPane.showMessageDialog(null,"Cliente já está cadastrado","Cadastro",JOptionPane.INFORMATION_MESSAGE );

        }else{
                JOptionPane.showMessageDialog(null,"CPF ou Email invalido!","Cadastro",JOptionPane.INFORMATION_MESSAGE );

        }
        
        
        
        
    }//GEN-LAST:event_BTNSalvarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
       int valorTabela = tabela.getSelectedRow();
       String stringCPF = (String)tabela.getValueAt(valorTabela, 1);
       
       Cliente cliente = this.clienteDAO.buscarCliente(stringCPF);
       
       txtNome.setText(cliente.getNome());
       txtCPF.setText(""+cliente.getCpf());
       txtTelefone.setText(cliente.getTelefone());
       txtEmail.setText(cliente.getEmail());
       txtEndereco.setText(cliente.getEndereco());
    }//GEN-LAST:event_tabelaMouseClicked

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
       txtNome.setText("");
       txtCPF.setText("");
       txtTelefone.setText("");
       txtEmail.setText("");
       txtEndereco.setText("");
    }//GEN-LAST:event_limparActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        int valorTabela = tabela.getSelectedRow();//seleciona linha da tabela 
        if(valorTabela >=0){// verifica se alguma linha foi selecionada se não retorna que não foi selecionado linhas. 
           int result = JOptionPane.showConfirmDialog(this, "Deseja Excluir cadastro", "Excluir",
                       JOptionPane.YES_NO_OPTION, //Botoes com variaveis prédefinidas 
                        JOptionPane.QUESTION_MESSAGE);
           
           if(result == JOptionPane.YES_NO_OPTION){
                String stringCPF = (String)tabela.getValueAt(valorTabela, 1); // pega valor da posição 1 da tabela 
                JOptionPane.showMessageDialog(null,this.clienteDAO.excluirCliente(stringCPF),"Cadastro",JOptionPane.INFORMATION_MESSAGE );                
                model.removeRow(valorTabela);
           }
        }else{
               JOptionPane.showMessageDialog(null,"Nenhum cadastro selecionado","Cadastro",JOptionPane.INFORMATION_MESSAGE ); 
           }
        
        
        
    }//GEN-LAST:event_excluirActionPerformed

    private void atualizarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarCadastroActionPerformed
        int valorTabela = tabela.getSelectedRow();
        
        
        

        
        if(valorTabela >=0){
            String stringCPF = (String)tabela.getValueAt(valorTabela, 1);
            String inputBoxCPF = txtCPF.getText();
                
            if(Objects.equals(stringCPF, inputBoxCPF)){
                
                int result = JOptionPane.showConfirmDialog(this, "Deseja Atualizar este cadastro ?", "Atualizar",
                             JOptionPane.YES_NO_OPTION, //Botoes com variaveis prédefinidas 
                             JOptionPane.QUESTION_MESSAGE);

                if(result == JOptionPane.YES_NO_OPTION  ){


                    String nome = txtNome.getText();
                    String cpf = txtCPF.getText();
                    String telefone = txtTelefone.getText();
                    String email = txtEmail.getText();
                    String endereco = txtEndereco.getText();               


                    if(!valid.isValidCampo(nome,cpf,telefone,email,endereco)){           
                    JOptionPane.showMessageDialog(null,"Campo invalido","Erro",JOptionPane.ERROR_MESSAGE );            
                    }

                    String retorno = clienteDAO.alterarCliente(nome, cpf, telefone, email, endereco);

                    if(retorno == "cpfInvalid"){
                         JOptionPane.showMessageDialog(null,"CPF informado invalido","Erro",JOptionPane.ERROR_MESSAGE );
                    }else if(retorno == "emailInvalid"){
                         JOptionPane.showMessageDialog(null,"Email informado invalido","Erro",JOptionPane.ERROR_MESSAGE );
                    }else if(retorno == "notFound"){
                         JOptionPane.showMessageDialog(null,"Não foi encontrado cadastro com o CPF informado","Erro",JOptionPane.ERROR_MESSAGE );

                    }else{
                        model.removeRow(valorTabela);
                        model.addRow(new Object[]{nome,cpf,telefone,email,endereco});
                        JOptionPane.showMessageDialog(null,"Cliente atualizado com sucesso","Alteracao cadastral",JOptionPane.INFORMATION_MESSAGE );

                    }    

                }
            }else{
               JOptionPane.showMessageDialog(null,"Cadastro selecionado não possui mesmo cpf informado","Cadastro",JOptionPane.INFORMATION_MESSAGE ); 

            }
            
        }else{
               JOptionPane.showMessageDialog(null,"Nenhuma linha selecionada","Cadastro",JOptionPane.INFORMATION_MESSAGE ); 
           }
    }//GEN-LAST:event_atualizarCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNSalvar;
    private javax.swing.JMenuItem JMenuItemSair;
    private javax.swing.JButton atualizarCadastro;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel jLabel1Nome;
    private javax.swing.JLabel jLabel1Nome1;
    private javax.swing.JLabel jLabel1Nome2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton limpar;
    private javax.swing.JTable tabela;
    private javax.swing.JTextPane txtCPF;
    private javax.swing.JTextPane txtEmail;
    private javax.swing.JTextArea txtEndereco;
    private javax.swing.JTextPane txtNome;
    private javax.swing.JTextPane txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void initCustomComponents() {
        model.addColumn("Nome");
        model.addColumn("CPF");
        model.addColumn("Telefone");
        model.addColumn("Email");
        model.addColumn("Endereço");
        
        tabela.setModel(model);
    }

    
}
